Update wasm-timer to wasmtimer
TrueLayer/reqwest-middleware pull request #202
Opened 2024-11-27 00:17 UTC by pvichivanives

Swaps over to wasmtimer, an updated library from wasm-timer which is not maintained.
Closes #199

2024-11-27 15:11 UTC, eopb requested changes
Thanks for the PR 🙌 

One thing needs to be changed

2024-11-27 15:11 UTC, eopb commented on reqwest-retry/Cargo.toml
> +wasmtimer = "0.4.1"
We need to gate this dependency behind `cfg(target_arch = "wasm32")` like we did before

2024-12-16 11:27 UTC, edevil commented
lgtm, but the change has conflicts now.

2025-01-23 20:38 UTC, eopb approved these changes

2025-01-29 00:19 UTC, pvichivanives commented
Do you want me to go in and fix the clippy issues? It be pretty unrelated to the pr.

2025-01-30 18:57 UTC, eopb commented
> Would you like me to fix the clippy issues? It seems pretty unrelated but I can mash it also into this PR.

Sorry for the late reply. The clippy lints are fine. They should be addressed in a separate  PR.

I'm more concerned about the CI job failing for the `cargo check` on wasm https://github.com/TrueLayer/reqwest-middleware/actions/runs/12937660406/job/36086067084?pr=202

Can you look at that?

2025-01-30 19:23 UTC, merged

2025-01-30 19:23 UTC, eopb commented
> Would you like me to fix the clippy issues? It seems pretty unrelated but I can mash it also into this PR.

No worries. Clippy can be fixed in another PR